---
namespace: infra
name: quay_configuration
version: 2.5.2
readme: README.md
authors:
  - Hervé Quatremain <herve.quatremain@redhat.com>
  - Tom Page <tpage@redhat.com>
description: Ansible modules to manage Quay Container Registry installations
license:
  - GPL-3.0-or-later
tags:
  - application
  - quay
  - registry
repository: https://github.com/redhat-cop/quay_configuration

# The URL to any online docs
documentation: https://github.com/redhat-cop/quay_configuration

# The URL to the home page of the collection/project
homepage: https://github.com/redhat-cop/quay_configuration

# The URL to the collection issue tracker
issues: https://github.com/redhat-cop/quay_configuration/issues
...
